
spring:
  data:
    mongodb:
      uri: ${sm://mongo-uri}
      authentication-database: ppm

server:
  port: ${PORT:8080}

logging:
  level:
    se:
      acrend:
        ppm: debug

    org:
      springframework: info
      mongodb: warn
    reactor: warn
