logging:
  level:
    se:
      acrend:
        ppm: debug

    org:
      springframework: warn
      mongodb: warn
    reactor: warn


spring:
  main:
    lazy-initialization: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
