
spring:
  data:
    mongodb:
      uri: mongodb+srv://johkin:dbpass@ppm.5tvva.gcp.mongodb.net/ppm?retryWrites=true&w=majority
      authentication-database: ppm

server:
  port: ${PORT:8080}

logging:
  level:
    se:
      acrend:
        ppm: debug

    org:
      springframework: info
      mongodb: warn
    reactor: warn
