version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ppm
      MONGO_INITDB_ROOT_PASSWORD: ppm

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ppm
      ME_CONFIG_MONGODB_ADMINPASSWORD: ppm
    depends_on: [mongo]
